/**
 * Lightweight DOM element picker.
 *
 * Drawn entirely from the content script: hover-highlight the element under
 * the cursor, click to commit, generate a stable CSS selector, then surface
 * the result so the caller can attach it to the right UserSiteRule field.
 *
 * Notes
 * - Selector generation prefers `id` and stable-looking `data-*` hooks over
 *   class names. Class names that look auto-generated (hash suffixes, BEM
 *   modifiers ending in random hex) are ignored to keep the rule durable
 *   across redeploys.
 * - The picker installs its own listeners on capture phase so it intercepts
 *   page clicks before the host site can redirect / submit a form.
 */

export interface PickerResult {
  /** Stable CSS selector that re-finds the element. */
  selector: string
  /** Visible text of the picked element, trimmed. Useful for the popup UI. */
  text: string
}

export type PickerCallback = (result: PickerResult | null) => void

const HIGHLIGHT_ATTR = 'data-bb-picker-highlight'
const OVERLAY_ID = 'bb-picker-overlay'

let active = false
let lastHighlight: Element | null = null
let onPick: PickerCallback | null = null

function ensureOverlay(): HTMLElement {
  let el = document.getElementById(OVERLAY_ID)
  if (el) return el
  el = document.createElement('div')
  el.id = OVERLAY_ID
  el.style.position = 'fixed'
  el.style.top = '12px'
  el.style.right = '12px'
  el.style.zIndex = '2147483647'
  el.style.padding = '8px 12px'
  el.style.background = 'rgba(20, 22, 35, 0.92)'
  el.style.color = '#fff'
  el.style.font = '12px/1.4 system-ui, sans-serif'
  el.style.borderRadius = '6px'
  el.style.pointerEvents = 'none'
  el.textContent = 'BelBucks: наведите на цену и кликните. Esc — отмена.'
  document.documentElement.appendChild(el)
  return el
}

function clearHighlight() {
  if (lastHighlight) {
    ;(lastHighlight as HTMLElement).removeAttribute(HIGHLIGHT_ATTR)
    lastHighlight = null
  }
}

function isAutoGeneratedClass(cls: string): boolean {
  // Webpack / styled-components / CSS modules tend to suffix hashes:
  //   styles_price__abc123, css-1xy2z3, sc-bdfBwQ
  // We don't trust those for long-lived selectors.
  if (/__[a-z0-9]{4,}$/i.test(cls)) return true
  if (/^css-[a-z0-9]{4,}$/i.test(cls)) return true
  if (/^sc-[a-zA-Z0-9]+$/i.test(cls)) return true
  return false
}

function pickStableClass(el: Element): string | null {
  const cls = el.classList ? Array.from(el.classList) : []
  for (const c of cls) {
    if (!c) continue
    if (isAutoGeneratedClass(c)) continue
    if (c.length > 60) continue
    return c
  }
  return null
}

/**
 * Generate a CSS selector that uniquely identifies `el` against `document`.
 * Algorithm:
 *   1. id → "#id"
 *   2. data-* hook (`data-testid`, `data-qaid`, `data-name`) → "tag[data-...]"
 *   3. tag.stableClass — verify uniqueness; if not unique, append :nth-of-type
 *   4. fallback: walk up to <body>, joining each step.
 */
export function generateSelector(el: Element): string {
  if (!(el instanceof Element)) return ''
  // 1. id
  if (el.id && /^[a-zA-Z_][\w-]*$/.test(el.id)) {
    const cand = `#${el.id}`
    try {
      if (document.querySelectorAll(cand).length === 1) return cand
    } catch {
      // ignore
    }
  }

  // 2. data-* hook
  const dataAttrs = ['data-testid', 'data-qaid', 'data-name', 'data-widget']
  for (const a of dataAttrs) {
    const v = el.getAttribute(a)
    if (!v) continue
    const cand = `${el.tagName.toLowerCase()}[${a}="${cssEscape(v)}"]`
    try {
      if (document.querySelectorAll(cand).length <= 3) return cand
    } catch {
      // ignore
    }
  }

  // 3. tag + stable class
  const cls = pickStableClass(el)
  if (cls) {
    const tag = el.tagName.toLowerCase()
    const cand = `${tag}.${cssEscape(cls)}`
    try {
      const matches = document.querySelectorAll(cand)
      if (matches.length === 1) return cand
      if (matches.length > 1 && el.parentElement) {
        const idx = Array.from(el.parentElement.children).indexOf(el) + 1
        return `${cand}:nth-child(${idx})`
      }
    } catch {
      // ignore
    }
  }

  // 4. fallback: ancestor path
  const parts: string[] = []
  let cur: Element | null = el
  while (cur && cur !== document.body && parts.length < 5) {
    const tag = cur.tagName.toLowerCase()
    const stable = pickStableClass(cur)
    if (stable) parts.unshift(`${tag}.${cssEscape(stable)}`)
    else if (cur.parentElement) {
      const idx = Array.from(cur.parentElement.children).indexOf(cur) + 1
      parts.unshift(`${tag}:nth-child(${idx})`)
    } else parts.unshift(tag)
    cur = cur.parentElement
  }
  return parts.join(' > ')
}

/**
 * CSS.escape isn't available in older WebViews. Implement a minimal version.
 */
function cssEscape(s: string): string {
  if (typeof CSS !== 'undefined' && typeof CSS.escape === 'function') {
    return CSS.escape(s)
  }
  return s.replace(/[^a-zA-Z0-9_\-]/g, (ch) => '\\' + ch)
}

function onMouseOver(ev: MouseEvent) {
  if (!active) return
  const target = ev.target as Element | null
  if (!target || target.id === OVERLAY_ID) return
  if (lastHighlight === target) return
  clearHighlight()
  ;(target as HTMLElement).setAttribute(HIGHLIGHT_ATTR, '1')
  lastHighlight = target
}

function onClickCapture(ev: MouseEvent) {
  if (!active) return
  const target = ev.target as Element | null
  if (!target || target.id === OVERLAY_ID) return
  ev.preventDefault()
  ev.stopImmediatePropagation()
  const selector = generateSelector(target)
  const text = (target.textContent || '').trim().slice(0, 80)
  finish({ selector, text })
}

function onKeyDown(ev: KeyboardEvent) {
  if (!active) return
  if (ev.key === 'Escape') finish(null)
}

function finish(result: PickerResult | null) {
  active = false
  clearHighlight()
  document.removeEventListener('mouseover', onMouseOver, true)
  document.removeEventListener('click', onClickCapture, true)
  document.removeEventListener('keydown', onKeyDown, true)
  document.getElementById(OVERLAY_ID)?.remove()
  document.getElementById('bb-picker-style')?.remove()
  const cb = onPick
  onPick = null
  cb?.(result)
}

function ensureStyles() {
  if (document.getElementById('bb-picker-style')) return
  const style = document.createElement('style')
  style.id = 'bb-picker-style'
  style.textContent = `
    [${HIGHLIGHT_ATTR}] {
      outline: 2px solid #ff5588 !important;
      outline-offset: 2px !important;
      cursor: crosshair !important;
    }
  `
  document.documentElement.appendChild(style)
}

export function startPicker(callback: PickerCallback): boolean {
  if (active) return false
  active = true
  onPick = callback
  ensureStyles()
  ensureOverlay()
  document.addEventListener('mouseover', onMouseOver, true)
  document.addEventListener('click', onClickCapture, true)
  document.addEventListener('keydown', onKeyDown, true)
  return true
}

export function isPickerActive(): boolean {
  return active
}
